### ISSUE TITLE
[PATCH] Fix spelling errors in manpage

### ISSUE THREAD

**Issue by carnil** [Abigail/Test-Regexp#1]
Hi,

In Debian we are currently applying the following patch to
Test-Regexp.
We thought you might be interested in it too.

```
Description: Fix spelling errors in manpage
Origin: vendor
Author: Salvatore Bonaccorso <carnil@debian.org>
Last-Update: 2016-06-02
```

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libtest-regexp-perl.git/plain/debian/patches/spelling-error-in-manpage.patch

Thanks for considering,
  Salvatore Bonaccorso,
  Debian Perl Group

**Comment by Abigail** [comment]
Thanks. This was applied in version 2016060501.
